name: Juno Static Checks
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18' ]
    name: Juno with Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Juno
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: make compile
